son1 = int(input("1-sonni kiriting:\n"))
son2 = int(input("2-sonni kiriting:\n"))
print(son1,"+",son2,"=", son1+son2)
print(son1,"-",son2,"=", son1-son2)
print(son1,"x",son2,"=", son1*son2)
print(son1,":",son2,"=", son1/son2)