davlat = ['uzb','rossiya','aqsh','kuba','xitoy','korea','angliya','baa']
print(davlat)
print(len(davlat))
print(sorted(davlat))
print(sorted(davlat,reverse=True))
print(davlat)
davlat.reverse()
print(davlat)
davlat.sort()
print(davlat)
davlat.sort(reverse=True)
print(davlat)